name: Game request
description: Request a game to be added to Art Class
assignees:
  - proudparrot2
body:
  - type: input
    id: game
    attributes:
      label: Game name
      description: What is the name of this game?
      placeholder: Flappy Bird
    validations:
      required: true
  - type: input
    id: is-it-elsewhere
    attributes:
      label: Is this game on any other game websites?
      description: If so, please put a link to it.
    validations:
      required: false
